# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_li4mohidDockWidgetBase(object):
    def setupUi(self, li4mohidDockWidgetBase):
        li4mohidDockWidgetBase.setObjectName("li4mohidDockWidgetBase")
        li4mohidDockWidgetBase.resize(469, 497)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.dockWidgetContents)
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 301, 87))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout_3 = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.labelCurrents = QtWidgets.QLabel(self.layoutWidget)
        self.labelCurrents.setObjectName("labelCurrents")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelCurrents)
        self.comboBoxHydro = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBoxHydro.setObjectName("comboBoxHydro")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxHydro)
        self.checkBoxWind = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBoxWind.setObjectName("checkBoxWind")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checkBoxWind)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_3.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.labelWinds = QtWidgets.QLabel(self.layoutWidget)
        self.labelWinds.setObjectName("labelWinds")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelWinds)
        self.comboBoxWind = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBoxWind.setEnabled(False)
        self.comboBoxWind.setObjectName("comboBoxWind")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBoxWind)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.widget)
        self.calendarWidget.setEnabled(True)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 200, 451, 211))
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setObjectName("calendarWidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.widget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 100, 301, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayoutDates = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayoutDates.setContentsMargins(0, 0, 0, 0)
        self.formLayoutDates.setObjectName("formLayoutDates")
        self.labelStart = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelStart.setObjectName("labelStart")
        self.formLayoutDates.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelStart)
        self.dateTimeEditStart = QtWidgets.QDateTimeEdit(self.formLayoutWidget)
        self.dateTimeEditStart.setDate(QtCore.QDate(2019, 10, 1))
        self.dateTimeEditStart.setCalendarPopup(True)
        self.dateTimeEditStart.setObjectName("dateTimeEditStart")
        self.formLayoutDates.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateTimeEditStart)
        self.labelEnd = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelEnd.setObjectName("labelEnd")
        self.formLayoutDates.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelEnd)
        self.dateTimeEditEnd = QtWidgets.QDateTimeEdit(self.formLayoutWidget)
        self.dateTimeEditEnd.setDate(QtCore.QDate(2019, 10, 1))
        self.dateTimeEditEnd.setCalendarPopup(True)
        self.dateTimeEditEnd.setObjectName("dateTimeEditEnd")
        self.formLayoutDates.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dateTimeEditEnd)
        self.applyButton = QtWidgets.QPushButton(self.widget)
        self.applyButton.setGeometry(QtCore.QRect(330, 30, 89, 25))
        self.applyButton.setObjectName("applyButton")
        self.runButton = QtWidgets.QPushButton(self.widget)
        self.runButton.setGeometry(QtCore.QRect(330, 120, 89, 25))
        self.runButton.setObjectName("runButton")
        self.labelFiles = QtWidgets.QLabel(self.widget)
        self.labelFiles.setGeometry(QtCore.QRect(0, 176, 111, 17))
        self.labelFiles.setObjectName("labelFiles")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(27, 418, 401, 41))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/plugins/li4mohid/Logo_plugin.png"))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        li4mohidDockWidgetBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(li4mohidDockWidgetBase)
        QtCore.QMetaObject.connectSlotsByName(li4mohidDockWidgetBase)

    def retranslateUi(self, li4mohidDockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        li4mohidDockWidgetBase.setWindowTitle(_translate("li4mohidDockWidgetBase", "LI4MOHID"))
        self.labelCurrents.setText(_translate("li4mohidDockWidgetBase", "Surface currents"))
        self.checkBoxWind.setText(_translate("li4mohidDockWidgetBase", "Enable wind forcing"))
        self.labelWinds.setText(_translate("li4mohidDockWidgetBase", "Wind Forcing"))
        self.labelStart.setText(_translate("li4mohidDockWidgetBase", "Start date:"))
        self.dateTimeEditStart.setDisplayFormat(_translate("li4mohidDockWidgetBase", "dd/MM/yyyy HH:mm"))
        self.labelEnd.setText(_translate("li4mohidDockWidgetBase", "End date:"))
        self.dateTimeEditEnd.setDisplayFormat(_translate("li4mohidDockWidgetBase", "dd/MM/yyyy  HH:mm"))
        self.applyButton.setText(_translate("li4mohidDockWidgetBase", "Apply"))
        self.runButton.setText(_translate("li4mohidDockWidgetBase", "Run"))
        self.labelFiles.setText(_translate("li4mohidDockWidgetBase", "Available files:"))

from . import resources
